### ISSUE TITLE
Papi Problem

### ISSUE THREAD

**Issue by successed** [Harieo/Seasons#14]
03.08.2019 - 21:30:55 - [TAB v2.5.0-pre3] PlaceholderAPI replace task failed. Please send this error to the FIRST author whose name or plugin name you see here:
03.08.2019 - 21:30:55 - java.lang.IllegalAccessError: uk/co/harieo/seasons/plugin/placeholders/SeasonsPlaceholderExpansion$RequestType
03.08.2019 - 21:30:55 -        at uk.co.harieo.seasons.plugin.placeholders.SeasonsPlaceholderExpansion.onPlaceholderRequest(SeasonsPlaceholderExpansion.java:53)
03.08.2019 - 21:30:55 -        at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:38)
03.08.2019 - 21:30:55 -        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:234)
03.08.2019 - 21:30:55 -        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:374)
03.08.2019 - 21:30:55 -        at me.neznamy.tab.bukkit.Placeholders.setPlaceholderAPIPlaceholders(Placeholders.java:110)
03.08.2019 - 21:30:55 -        at me.neznamy.tab.bukkit.Placeholders.replace(Placeholders.java:102)
03.08.2019 - 21:30:55 -        at me.neznamy.tab.shared.Placeholders.replace(Placeholders.java:90)
03.08.2019 - 21:30:55 -        at me.neznamy.tab.shared.Placeholders.replaceMultiple(Placeholders.java:78)
03.08.2019 - 21:30:55 -        at me.neznamy.tab.shared.HeaderFooter.refreshHeaderFooter(HeaderFooter.java:29)
03.08.2019 - 21:30:55 -        at me.neznamy.tab.shared.HeaderFooter$1.run(HeaderFooter.java:14)
03.08.2019 - 21:30:55 -        at me.neznamy.tab.shared.Shared$2.run(Shared.java:132)
03.08.2019 - 21:30:55 -        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
03.08.2019 - 21:30:55 -        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
03.08.2019 - 21:30:55 -        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
03.08.2019 - 21:30:55 -        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
03.08.2019 - 21:30:55 -        at java.lang.Thread.run(Thread.java:748)

**Comment by Harieo** [comment]
Please can I ask how you were using PlaceholderAPI at the time the error occurred? 

- What placeholder were you trying to use?
- Is your PlaceholderAPI version the latest version on Spigot?
- Were you doing anything else that may have affected it?

**Comment by successed** [comment]
Placeholder : '&aMevsim: &f%seasons_season_world%'

i have TAB_v2.5.0 plugin and this plugin support papi and i add tab plugin config this error.

my papi : PlaceholderAPI-2.10.3
my tab : TAB_v2.5.0
server version 1.14.4 paper:156

**Comment by Harieo** [comment]
I will look into the issue, I'm not quite sure off the top of my head.

**Comment by Harieo** [comment]
This bug could not be replicated and seems to be a problem with another plugin that you're using. All I can suggest is making sure everything is updated to the highest version and possibly raising the issue with the plugin developer for your TAB plugin. 

Feel free to direct their developers here if they could shed light on this issue!
