### ISSUE TITLE
Seasons overriding effects of Beacons.

### ISSUE THREAD

**Issue by DilanRona** [Harieo/Seasons#19]
Some of the players on my server complained that the seasons plugin is overriding the effect of Beacons placed. Even at full power. Intended behaviour?

**Comment by Harieo** [comment]
Could you define which effects no longer work from beacons when Seasons is active?

**Comment by DilanRona** [comment]
From what I understand it is regeneration, its nullified when its a thunderstorm due to the seasons plugin

**Comment by Harieo** [comment]
I understand, the behaviour was not considered when making the thunderstorm weather and I am not sure whether to keep it as a feature. I personally think it is a good mechanic as the idea of the thunderstorm was to stay indoors and essentially "wait out the storm." Also, it is possible to disable the weather via the configuration file if it is not liked by players.

As you raised the issue, what do you think about it? Opinions are always appreciated!

**Comment by DilanRona** [comment]
Best way to get the information you need is to actually talk to the players that raised the issue.

 https://discord.gg/WwHKzKM

**Comment by DilanRona** [comment]
personally i think its ok the way it is now, but perhaps a config option to control that aspect may help

**Comment by Harieo** [comment]
I'll mark this as needs discussion and discuss with others what they think of it. I'll post the result on this issue when I have one!

**Comment by Harieo** [comment]
This issue has been marked as an enchancement and will be added to Seasons

**Comment by Harieo** [comment]
This suggestion has been implemented as of the v2.4.0 update. Thank you for helping make Seasons better!
