### ISSUE TITLE
Rain affecting dirt, and grass paths under cover.

### ISSUE THREAD

**Issue by DilanRona** [Harieo/Seasons#20]
Had complaints that dirt and grass paths that is not actively rained on, is affected by slowness when it is raining. 10 blocks deep even where the rain never reach.

**Comment by Harieo** [comment]
Currently, this is intended behaviour due to wishing to limit advanced calculations in a move event (can become laggy). However, I will mark this as an Enhancement for a possible future update!

**Comment by Harieo** [comment]
This enhancement has been added in Version 2.3.0
