### ISSUE TITLE
Seasons plugin overrides effect of potions during storms

### ISSUE THREAD

**Issue by DilanRona** [Harieo/Seasons#23]
Had a complaint on my server that regeneration potions are not working during storms. Intended behavior, or bug?

**Comment by Harieo** [comment]
The storm weather disables ALL regeneration of any kind, natural or not. This includes beacons, potions and anything else that augments health. I am currently considering whether to change this in the next update, in the meantime, you can disable storms in the configuration if it becomes too much of a problem for your server!

**Comment by Harieo** [comment]
This issue has been marked as an enchancement and will be added to Seasons

**Comment by Harieo** [comment]
This suggestion has been implemented as of the v2.4.0 update. Thank you for helping make Seasons better!
