### ISSUE TITLE
[Feature Request] Ability to disable message(s) from showing via the lang.yml file

### ISSUE THREAD

**Issue by iCaitlyn** [Harieo/Seasons#28]
**Issue type:** Feature Request
--------------------------------------------------------------
**Summary:** Ability to disable one or more messages showing, by giving it an empty string or [ ]

Example: 
![image](https://user-images.githubusercontent.com/55845572/65700158-bf032b80-e0b1-11e9-91f3-66a7f1a29a15.png)

**Comment by Harieo** [comment]
This suggestion has been implemented as of the v2.4.0 update. Thank you for helping make Seasons better!
