### ISSUE TITLE
[Feature Request] Disable damage taken when on hot sand or in water whilst in vehicles/mounted

### ISSUE THREAD

**Issue by iCaitlyn** [Harieo/Seasons#29]
**Issue type:** Feature Request
--------------------------------------------------------------
**Summary:** Permanently disable damage taken from "hot sand" and similar when riding a horse/vehicle

**Comment by Harieo** [comment]
This issue affects the following effects: Strong Current, The Shivers, Wet Mud and Hot Sand.

**Comment by Harieo** [comment]
This suggestion has been implemented as of the v2.4.0 update. Thank you for helping make Seasons better!
