### ISSUE TITLE
When sleeping in a bed seasons wont change

### ISSUE THREAD

**Issue by Blobbie01** [Harieo/Seasons#3]
Hey there :)

When sleeping in a bed seasons wont change, it just goes on as the same day before,
Is it possible you can patch this? I love the plugin on my survival server :))

**Comment by Harieo** [comment]
Hi, sorry to hear that Seasons has broken for you. I'm going to need some extra information to be able to help:

What server version are you using? (e.g 1.12.2)
Do you use any plugins that may alter sleeping or time changes? If so, which plugins?
And just to clarify, there is no problem with the weather or day changing when sleeping? Only season changes?

Regards,
Harieo

**Comment by Blobbie01** [comment]
Hey :)

Thanks for the fast respond!
Im using 1.12.2, i have the plugins essentials installed but i dont think that affects it, 
Day and weather changes fine when sleeping yea :) just the season (eg summer warm) and the season day stays the same


Regards,
A big fan 😄

**Comment by Harieo** [comment]
Alright, I'll look into it. Thanks for taking the time to raise this as an issue!

**Comment by Blobbie01** [comment]
Hey :)

I updated essentials and reinstalled seasons and it seems to be working fine now!
Sorry for wasting ur time :/

**Comment by Harieo** [comment]
Alright, if you experience the error again then feel free to re-open this issue. You may also have been using an outdated version of seasons as such bugs have been found in the past.

Issue #3 is hereby closed as it was found on an outdated version. This issue may be re-opened if the bug is found on the latest version.
