### ISSUE TITLE
Hat blowing off and item deletion

### ISSUE THREAD

**Issue by docHP** [Harieo/Seasons#37]
Every time you craft something and separate items using SHIFT with a hat on your head it will automatically say that the hat blew off and then where you had that item the hat will show up and delete your previous item.

**Comment by docHP** [comment]
Update: Using shift and spreading out items of any kind leads to this behavior.

**Comment by Harieo** [comment]
This issue has been confirmed and will be fixed in the next update

**Comment by Harieo** [comment]
This issue has been fixed as of the v2.4.0 release. If you experience this issue in future, feel free to make a new issue!
